###
POST  http://localhost:3003/galodio/signup
Content-Type: application/json

{
    "nome": "Lucas Txai",
    "sobrenome": "Fonceca",
    "email": "txaifonceca@gmail.com",
    "telefone": "48996485945",
    "apelido": "Txai",
    "senha": "W8B73uTN^^Yl",
    "role": "ADMIN"
}

###
POST  http://localhost:3003/galodio/login
Content-Type: application/json

{
    "email": "txaifonceca@gmail.com",
    "senha": "W8B73uTN^^Yl"
}

###
GET http://localhost:3003/bolodio/jogos
Content-Type: application/json